export type EmojiCategory =
  | 'Smileys'
  | 'People'
  | 'Nature'
  | 'Food'
  | 'Activities'
  | 'Travel'
  | 'Objects'
  | 'Symbols'

export type EmojiEntry = {
  emoji: string
  name: string
  keywords: string[]
  category: EmojiCategory
}

const RECENTLY_USED_KEY = 'markitor-recent-emojis'
const MAX_RECENT = 24

export const CATEGORIES: EmojiCategory[] = [
  'Smileys',
  'People',
  'Nature',
  'Food',
  'Activities',
  'Travel',
  'Objects',
  'Symbols',
]

// ~600 commonly-used emojis
const EMOJI_DATA: EmojiEntry[] = [
  // Smileys
  { emoji: '😀', name: 'grinning face', keywords: ['happy', 'smile', 'grin'], category: 'Smileys' },
  { emoji: '😃', name: 'grinning face with big eyes', keywords: ['happy', 'smile'], category: 'Smileys' },
  { emoji: '😄', name: 'grinning face with smiling eyes', keywords: ['happy', 'joy'], category: 'Smileys' },
  { emoji: '😁', name: 'beaming face', keywords: ['happy', 'grin', 'smile'], category: 'Smileys' },
  { emoji: '😆', name: 'grinning squinting face', keywords: ['laugh', 'happy'], category: 'Smileys' },
  { emoji: '😅', name: 'grinning face with sweat', keywords: ['nervous', 'laugh'], category: 'Smileys' },
  { emoji: '🤣', name: 'rolling on the floor laughing', keywords: ['lol', 'laugh', 'rofl'], category: 'Smileys' },
  { emoji: '😂', name: 'face with tears of joy', keywords: ['laugh', 'cry', 'happy'], category: 'Smileys' },
  { emoji: '🙂', name: 'slightly smiling face', keywords: ['smile', 'ok'], category: 'Smileys' },
  { emoji: '🙃', name: 'upside-down face', keywords: ['silly', 'sarcasm'], category: 'Smileys' },
  { emoji: '😉', name: 'winking face', keywords: ['wink', 'flirt'], category: 'Smileys' },
  { emoji: '😊', name: 'smiling face with smiling eyes', keywords: ['happy', 'blush', 'cute'], category: 'Smileys' },
  { emoji: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent'], category: 'Smileys' },
  { emoji: '🥰', name: 'smiling face with hearts', keywords: ['love', 'adore'], category: 'Smileys' },
  { emoji: '😍', name: 'heart eyes', keywords: ['love', 'crush', 'adore'], category: 'Smileys' },
  { emoji: '🤩', name: 'star struck', keywords: ['excited', 'wow', 'star'], category: 'Smileys' },
  { emoji: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love'], category: 'Smileys' },
  { emoji: '😗', name: 'kissing face', keywords: ['kiss'], category: 'Smileys' },
  { emoji: '😚', name: 'kissing face with closed eyes', keywords: ['kiss', 'love'], category: 'Smileys' },
  { emoji: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss'], category: 'Smileys' },
  { emoji: '🥲', name: 'smiling face with tear', keywords: ['sad', 'happy', 'grateful'], category: 'Smileys' },
  { emoji: '😋', name: 'face savoring food', keywords: ['yummy', 'delicious', 'tongue'], category: 'Smileys' },
  { emoji: '😛', name: 'face with tongue', keywords: ['tongue', 'playful'], category: 'Smileys' },
  { emoji: '😜', name: 'winking face with tongue', keywords: ['tongue', 'wink', 'silly'], category: 'Smileys' },
  { emoji: '🤪', name: 'zany face', keywords: ['crazy', 'wild', 'silly'], category: 'Smileys' },
  { emoji: '😝', name: 'squinting face with tongue', keywords: ['tongue', 'playful'], category: 'Smileys' },
  { emoji: '🤑', name: 'money mouth face', keywords: ['money', 'rich', 'dollar'], category: 'Smileys' },
  { emoji: '🤗', name: 'hugging face', keywords: ['hug', 'warm'], category: 'Smileys' },
  { emoji: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'giggle'], category: 'Smileys' },
  { emoji: '🤫', name: 'shushing face', keywords: ['quiet', 'secret', 'shh'], category: 'Smileys' },
  { emoji: '🤔', name: 'thinking face', keywords: ['think', 'hmm', 'wonder'], category: 'Smileys' },
  { emoji: '🤐', name: 'zipper mouth face', keywords: ['quiet', 'secret', 'zip'], category: 'Smileys' },
  { emoji: '🤨', name: 'face with raised eyebrow', keywords: ['suspicious', 'skeptical'], category: 'Smileys' },
  { emoji: '😐', name: 'neutral face', keywords: ['meh', 'blank'], category: 'Smileys' },
  { emoji: '😑', name: 'expressionless face', keywords: ['blank', 'meh'], category: 'Smileys' },
  { emoji: '😶', name: 'face without mouth', keywords: ['mute', 'silent'], category: 'Smileys' },
  { emoji: '😏', name: 'smirking face', keywords: ['smirk', 'flirt'], category: 'Smileys' },
  { emoji: '😒', name: 'unamused face', keywords: ['bored', 'meh'], category: 'Smileys' },
  { emoji: '🙄', name: 'rolling eyes', keywords: ['whatever', 'annoyed'], category: 'Smileys' },
  { emoji: '😬', name: 'grimacing face', keywords: ['awkward', 'nervous'], category: 'Smileys' },
  { emoji: '🤥', name: 'lying face', keywords: ['lie', 'pinocchio'], category: 'Smileys' },
  { emoji: '😌', name: 'relieved face', keywords: ['relieved', 'calm', 'peace'], category: 'Smileys' },
  { emoji: '😔', name: 'pensive face', keywords: ['sad', 'down'], category: 'Smileys' },
  { emoji: '😪', name: 'sleepy face', keywords: ['tired', 'sleep'], category: 'Smileys' },
  { emoji: '🤤', name: 'drooling face', keywords: ['drool', 'hungry'], category: 'Smileys' },
  { emoji: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz', 'tired'], category: 'Smileys' },
  { emoji: '😷', name: 'face with medical mask', keywords: ['mask', 'sick', 'covid'], category: 'Smileys' },
  { emoji: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever', 'ill'], category: 'Smileys' },
  { emoji: '🤕', name: 'face with head bandage', keywords: ['hurt', 'injured'], category: 'Smileys' },
  { emoji: '🤢', name: 'nauseated face', keywords: ['sick', 'gross', 'nausea'], category: 'Smileys' },
  { emoji: '🤮', name: 'face vomiting', keywords: ['sick', 'vomit', 'gross'], category: 'Smileys' },
  { emoji: '🥵', name: 'hot face', keywords: ['hot', 'heat', 'sweat'], category: 'Smileys' },
  { emoji: '🥶', name: 'cold face', keywords: ['cold', 'freezing'], category: 'Smileys' },
  { emoji: '🥴', name: 'woozy face', keywords: ['dizzy', 'drunk'], category: 'Smileys' },
  { emoji: '😵', name: 'face with crossed-out eyes', keywords: ['dizzy', 'dead'], category: 'Smileys' },
  { emoji: '🤯', name: 'exploding head', keywords: ['mind blown', 'shocked', 'wow'], category: 'Smileys' },
  { emoji: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'western'], category: 'Smileys' },
  { emoji: '🥳', name: 'partying face', keywords: ['party', 'celebrate'], category: 'Smileys' },
  { emoji: '🥸', name: 'disguised face', keywords: ['disguise', 'incognito'], category: 'Smileys' },
  { emoji: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'sunglasses'], category: 'Smileys' },
  { emoji: '🤓', name: 'nerd face', keywords: ['nerd', 'geek', 'glasses'], category: 'Smileys' },
  { emoji: '🧐', name: 'face with monocle', keywords: ['monocle', 'inspect', 'investigate'], category: 'Smileys' },
  { emoji: '😕', name: 'confused face', keywords: ['confused', 'unsure'], category: 'Smileys' },
  { emoji: '😟', name: 'worried face', keywords: ['worried', 'concern'], category: 'Smileys' },
  { emoji: '🙁', name: 'slightly frowning face', keywords: ['sad', 'frown'], category: 'Smileys' },
  { emoji: '😮', name: 'face with open mouth', keywords: ['surprised', 'wow', 'oh'], category: 'Smileys' },
  { emoji: '😯', name: 'hushed face', keywords: ['surprised', 'quiet'], category: 'Smileys' },
  { emoji: '😲', name: 'astonished face', keywords: ['shocked', 'surprised', 'amazed'], category: 'Smileys' },
  { emoji: '😳', name: 'flushed face', keywords: ['embarrassed', 'blush'], category: 'Smileys' },
  { emoji: '🥺', name: 'pleading face', keywords: ['please', 'puppy eyes', 'beg'], category: 'Smileys' },
  { emoji: '😦', name: 'frowning face with open mouth', keywords: ['sad', 'shocked'], category: 'Smileys' },
  { emoji: '😧', name: 'anguished face', keywords: ['anguish', 'distress'], category: 'Smileys' },
  { emoji: '😨', name: 'fearful face', keywords: ['scared', 'fear'], category: 'Smileys' },
  { emoji: '😰', name: 'anxious face with sweat', keywords: ['anxious', 'nervous'], category: 'Smileys' },
  { emoji: '😥', name: 'sad but relieved face', keywords: ['sad', 'relieved'], category: 'Smileys' },
  { emoji: '😢', name: 'crying face', keywords: ['cry', 'sad', 'tear'], category: 'Smileys' },
  { emoji: '😭', name: 'loudly crying face', keywords: ['cry', 'sob', 'sad'], category: 'Smileys' },
  { emoji: '😱', name: 'face screaming in fear', keywords: ['scream', 'scared', 'horror'], category: 'Smileys' },
  { emoji: '😖', name: 'confounded face', keywords: ['frustrated', 'quiver'], category: 'Smileys' },
  { emoji: '😣', name: 'persevering face', keywords: ['struggle', 'frustrated'], category: 'Smileys' },
  { emoji: '😞', name: 'disappointed face', keywords: ['sad', 'disappointed'], category: 'Smileys' },
  { emoji: '😓', name: 'downcast face with sweat', keywords: ['sad', 'sweat'], category: 'Smileys' },
  { emoji: '😩', name: 'weary face', keywords: ['tired', 'frustrated'], category: 'Smileys' },
  { emoji: '😫', name: 'tired face', keywords: ['tired', 'exhausted'], category: 'Smileys' },
  { emoji: '🥱', name: 'yawning face', keywords: ['yawn', 'tired', 'bored'], category: 'Smileys' },
  { emoji: '😤', name: 'face with steam from nose', keywords: ['angry', 'triumph', 'huff'], category: 'Smileys' },
  { emoji: '😡', name: 'pouting face', keywords: ['angry', 'mad', 'rage'], category: 'Smileys' },
  { emoji: '😠', name: 'angry face', keywords: ['angry', 'mad'], category: 'Smileys' },
  { emoji: '🤬', name: 'face with symbols on mouth', keywords: ['swear', 'angry', 'curse'], category: 'Smileys' },
  { emoji: '😈', name: 'smiling face with horns', keywords: ['devil', 'evil', 'mischief'], category: 'Smileys' },
  { emoji: '👿', name: 'angry face with horns', keywords: ['devil', 'angry'], category: 'Smileys' },
  { emoji: '💀', name: 'skull', keywords: ['dead', 'death', 'skeleton'], category: 'Smileys' },
  { emoji: '☠️', name: 'skull and crossbones', keywords: ['death', 'danger', 'poison'], category: 'Smileys' },
  { emoji: '💩', name: 'pile of poo', keywords: ['poop', 'shit'], category: 'Smileys' },
  { emoji: '🤡', name: 'clown face', keywords: ['clown', 'silly'], category: 'Smileys' },
  { emoji: '👹', name: 'ogre', keywords: ['monster', 'demon'], category: 'Smileys' },
  { emoji: '👻', name: 'ghost', keywords: ['ghost', 'halloween', 'boo'], category: 'Smileys' },
  { emoji: '👽', name: 'alien', keywords: ['alien', 'ufo', 'space'], category: 'Smileys' },
  { emoji: '🤖', name: 'robot', keywords: ['robot', 'bot', 'ai'], category: 'Smileys' },
  { emoji: '😺', name: 'grinning cat', keywords: ['cat', 'happy'], category: 'Smileys' },
  { emoji: '😸', name: 'grinning cat with smiling eyes', keywords: ['cat', 'happy'], category: 'Smileys' },
  { emoji: '😹', name: 'cat with tears of joy', keywords: ['cat', 'laugh'], category: 'Smileys' },
  { emoji: '😻', name: 'smiling cat with heart eyes', keywords: ['cat', 'love'], category: 'Smileys' },
  { emoji: '🙈', name: 'see-no-evil monkey', keywords: ['monkey', 'shy', 'hide'], category: 'Smileys' },
  { emoji: '🙉', name: 'hear-no-evil monkey', keywords: ['monkey', 'ignore'], category: 'Smileys' },
  { emoji: '🙊', name: 'speak-no-evil monkey', keywords: ['monkey', 'quiet', 'oops'], category: 'Smileys' },

  // People
  { emoji: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'bye', 'hi'], category: 'People' },
  { emoji: '🤚', name: 'raised back of hand', keywords: ['hand', 'stop'], category: 'People' },
  { emoji: '🖐️', name: 'hand with fingers splayed', keywords: ['hand', 'five', 'high five'], category: 'People' },
  { emoji: '✋', name: 'raised hand', keywords: ['hand', 'stop', 'high five'], category: 'People' },
  { emoji: '🖖', name: 'vulcan salute', keywords: ['spock', 'star trek'], category: 'People' },
  { emoji: '👌', name: 'OK hand', keywords: ['ok', 'perfect', 'good'], category: 'People' },
  { emoji: '🤌', name: 'pinched fingers', keywords: ['italian', 'what', 'gesture'], category: 'People' },
  { emoji: '🤏', name: 'pinching hand', keywords: ['small', 'tiny', 'little'], category: 'People' },
  { emoji: '✌️', name: 'victory hand', keywords: ['peace', 'victory', 'two'], category: 'People' },
  { emoji: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope', 'fingers crossed'], category: 'People' },
  { emoji: '🤟', name: 'love you gesture', keywords: ['love', 'rock'], category: 'People' },
  { emoji: '🤘', name: 'sign of the horns', keywords: ['rock', 'metal'], category: 'People' },
  { emoji: '🤙', name: 'call me hand', keywords: ['call', 'shaka', 'hang loose'], category: 'People' },
  { emoji: '👈', name: 'backhand index pointing left', keywords: ['left', 'point'], category: 'People' },
  { emoji: '👉', name: 'backhand index pointing right', keywords: ['right', 'point'], category: 'People' },
  { emoji: '👆', name: 'backhand index pointing up', keywords: ['up', 'point'], category: 'People' },
  { emoji: '🖕', name: 'middle finger', keywords: ['finger', 'rude'], category: 'People' },
  { emoji: '👇', name: 'backhand index pointing down', keywords: ['down', 'point'], category: 'People' },
  { emoji: '☝️', name: 'index pointing up', keywords: ['up', 'point', 'one'], category: 'People' },
  { emoji: '👍', name: 'thumbs up', keywords: ['yes', 'good', 'like', 'approve', 'ok'], category: 'People' },
  { emoji: '👎', name: 'thumbs down', keywords: ['no', 'bad', 'dislike', 'disapprove'], category: 'People' },
  { emoji: '✊', name: 'raised fist', keywords: ['fist', 'power', 'punch'], category: 'People' },
  { emoji: '👊', name: 'oncoming fist', keywords: ['punch', 'fist bump'], category: 'People' },
  { emoji: '🤛', name: 'left-facing fist', keywords: ['fist bump'], category: 'People' },
  { emoji: '🤜', name: 'right-facing fist', keywords: ['fist bump'], category: 'People' },
  { emoji: '👏', name: 'clapping hands', keywords: ['clap', 'applause', 'bravo'], category: 'People' },
  { emoji: '🙌', name: 'raising hands', keywords: ['celebrate', 'hooray', 'yay'], category: 'People' },
  { emoji: '👐', name: 'open hands', keywords: ['hands', 'open'], category: 'People' },
  { emoji: '🤲', name: 'palms up together', keywords: ['pray', 'offer'], category: 'People' },
  { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agree', 'shake'], category: 'People' },
  { emoji: '🙏', name: 'folded hands', keywords: ['pray', 'please', 'thanks', 'hope'], category: 'People' },
  { emoji: '✍️', name: 'writing hand', keywords: ['write', 'pen'], category: 'People' },
  { emoji: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle', 'arm', 'flex'], category: 'People' },
  { emoji: '🦾', name: 'mechanical arm', keywords: ['robot', 'prosthetic'], category: 'People' },
  { emoji: '🦿', name: 'mechanical leg', keywords: ['robot', 'prosthetic'], category: 'People' },
  { emoji: '🦵', name: 'leg', keywords: ['kick', 'limb'], category: 'People' },
  { emoji: '🦶', name: 'foot', keywords: ['kick', 'stomp'], category: 'People' },
  { emoji: '👂', name: 'ear', keywords: ['hear', 'listen', 'sound'], category: 'People' },
  { emoji: '👃', name: 'nose', keywords: ['smell', 'sniff'], category: 'People' },
  { emoji: '🧠', name: 'brain', keywords: ['think', 'smart', 'mind', 'intelligence'], category: 'People' },
  { emoji: '👀', name: 'eyes', keywords: ['look', 'see', 'watch', 'stare'], category: 'People' },
  { emoji: '👁️', name: 'eye', keywords: ['look', 'see'], category: 'People' },
  { emoji: '👅', name: 'tongue', keywords: ['taste', 'lick'], category: 'People' },
  { emoji: '👄', name: 'mouth', keywords: ['lips', 'kiss'], category: 'People' },
  { emoji: '👶', name: 'baby', keywords: ['baby', 'child', 'infant'], category: 'People' },
  { emoji: '🧑', name: 'person', keywords: ['adult', 'person'], category: 'People' },
  { emoji: '👦', name: 'boy', keywords: ['boy', 'child', 'kid'], category: 'People' },
  { emoji: '👧', name: 'girl', keywords: ['girl', 'child', 'kid'], category: 'People' },
  { emoji: '🧑‍💻', name: 'technologist', keywords: ['developer', 'coder', 'programmer', 'computer'], category: 'People' },
  { emoji: '👨‍💻', name: 'man technologist', keywords: ['developer', 'coder', 'programmer'], category: 'People' },
  { emoji: '👩‍💻', name: 'woman technologist', keywords: ['developer', 'coder', 'programmer'], category: 'People' },
  { emoji: '🧑‍🎓', name: 'student', keywords: ['student', 'graduate', 'school'], category: 'People' },
  { emoji: '🧑‍🏫', name: 'teacher', keywords: ['teacher', 'professor'], category: 'People' },
  { emoji: '🧑‍🔬', name: 'scientist', keywords: ['scientist', 'lab', 'research'], category: 'People' },
  { emoji: '🧑‍🚀', name: 'astronaut', keywords: ['space', 'astronaut'], category: 'People' },
  { emoji: '🧑‍🎨', name: 'artist', keywords: ['artist', 'paint', 'creative'], category: 'People' },
  { emoji: '🧑‍🍳', name: 'cook', keywords: ['chef', 'cook', 'kitchen'], category: 'People' },
  { emoji: '💃', name: 'woman dancing', keywords: ['dance', 'salsa'], category: 'People' },
  { emoji: '🕺', name: 'man dancing', keywords: ['dance', 'disco'], category: 'People' },
  { emoji: '🏃', name: 'person running', keywords: ['run', 'exercise', 'jog'], category: 'People' },

  // Nature
  { emoji: '🐶', name: 'dog face', keywords: ['dog', 'puppy', 'pet'], category: 'Nature' },
  { emoji: '🐱', name: 'cat face', keywords: ['cat', 'kitten', 'pet'], category: 'Nature' },
  { emoji: '🐭', name: 'mouse face', keywords: ['mouse', 'rodent'], category: 'Nature' },
  { emoji: '🐹', name: 'hamster', keywords: ['hamster', 'pet'], category: 'Nature' },
  { emoji: '🐰', name: 'rabbit face', keywords: ['rabbit', 'bunny'], category: 'Nature' },
  { emoji: '🦊', name: 'fox', keywords: ['fox', 'animal'], category: 'Nature' },
  { emoji: '🐻', name: 'bear', keywords: ['bear', 'animal'], category: 'Nature' },
  { emoji: '🐼', name: 'panda', keywords: ['panda', 'bear', 'cute'], category: 'Nature' },
  { emoji: '🐨', name: 'koala', keywords: ['koala', 'animal', 'cute'], category: 'Nature' },
  { emoji: '🐯', name: 'tiger face', keywords: ['tiger', 'cat'], category: 'Nature' },
  { emoji: '🦁', name: 'lion', keywords: ['lion', 'king', 'cat'], category: 'Nature' },
  { emoji: '🐮', name: 'cow face', keywords: ['cow', 'moo'], category: 'Nature' },
  { emoji: '🐷', name: 'pig face', keywords: ['pig', 'oink'], category: 'Nature' },
  { emoji: '🐸', name: 'frog', keywords: ['frog', 'toad'], category: 'Nature' },
  { emoji: '🐵', name: 'monkey face', keywords: ['monkey', 'ape'], category: 'Nature' },
  { emoji: '🐔', name: 'chicken', keywords: ['chicken', 'bird'], category: 'Nature' },
  { emoji: '🐧', name: 'penguin', keywords: ['penguin', 'bird', 'cold'], category: 'Nature' },
  { emoji: '🐦', name: 'bird', keywords: ['bird', 'tweet'], category: 'Nature' },
  { emoji: '🦅', name: 'eagle', keywords: ['eagle', 'bird', 'freedom'], category: 'Nature' },
  { emoji: '🦆', name: 'duck', keywords: ['duck', 'bird', 'quack'], category: 'Nature' },
  { emoji: '🦉', name: 'owl', keywords: ['owl', 'bird', 'wisdom', 'night'], category: 'Nature' },
  { emoji: '🐺', name: 'wolf', keywords: ['wolf', 'howl'], category: 'Nature' },
  { emoji: '🐗', name: 'boar', keywords: ['boar', 'pig', 'wild'], category: 'Nature' },
  { emoji: '🐴', name: 'horse face', keywords: ['horse', 'pony'], category: 'Nature' },
  { emoji: '🦄', name: 'unicorn', keywords: ['unicorn', 'magic', 'fantasy'], category: 'Nature' },
  { emoji: '🐝', name: 'honeybee', keywords: ['bee', 'honey', 'buzz'], category: 'Nature' },
  { emoji: '🪱', name: 'worm', keywords: ['worm', 'bug'], category: 'Nature' },
  { emoji: '🐛', name: 'bug', keywords: ['bug', 'insect', 'caterpillar'], category: 'Nature' },
  { emoji: '🦋', name: 'butterfly', keywords: ['butterfly', 'insect', 'pretty'], category: 'Nature' },
  { emoji: '🐌', name: 'snail', keywords: ['snail', 'slow'], category: 'Nature' },
  { emoji: '🐞', name: 'lady beetle', keywords: ['ladybug', 'insect'], category: 'Nature' },
  { emoji: '🐜', name: 'ant', keywords: ['ant', 'insect'], category: 'Nature' },
  { emoji: '🐢', name: 'turtle', keywords: ['turtle', 'slow'], category: 'Nature' },
  { emoji: '🐍', name: 'snake', keywords: ['snake', 'reptile'], category: 'Nature' },
  { emoji: '🦎', name: 'lizard', keywords: ['lizard', 'reptile'], category: 'Nature' },
  { emoji: '🐙', name: 'octopus', keywords: ['octopus', 'ocean', 'sea'], category: 'Nature' },
  { emoji: '🦀', name: 'crab', keywords: ['crab', 'cancer', 'ocean'], category: 'Nature' },
  { emoji: '🐬', name: 'dolphin', keywords: ['dolphin', 'ocean', 'sea'], category: 'Nature' },
  { emoji: '🐳', name: 'spouting whale', keywords: ['whale', 'ocean'], category: 'Nature' },
  { emoji: '🦈', name: 'shark', keywords: ['shark', 'ocean', 'danger'], category: 'Nature' },
  { emoji: '🐊', name: 'crocodile', keywords: ['crocodile', 'alligator'], category: 'Nature' },
  { emoji: '🦕', name: 'sauropod', keywords: ['dinosaur', 'dino'], category: 'Nature' },
  { emoji: '🦖', name: 't-rex', keywords: ['dinosaur', 'dino', 'trex'], category: 'Nature' },
  { emoji: '💐', name: 'bouquet', keywords: ['flowers', 'bouquet', 'gift'], category: 'Nature' },
  { emoji: '🌸', name: 'cherry blossom', keywords: ['flower', 'spring', 'sakura'], category: 'Nature' },
  { emoji: '🌹', name: 'rose', keywords: ['flower', 'love', 'rose', 'red'], category: 'Nature' },
  { emoji: '🌺', name: 'hibiscus', keywords: ['flower', 'tropical'], category: 'Nature' },
  { emoji: '🌻', name: 'sunflower', keywords: ['flower', 'sun', 'yellow'], category: 'Nature' },
  { emoji: '🌼', name: 'blossom', keywords: ['flower', 'bloom'], category: 'Nature' },
  { emoji: '🌷', name: 'tulip', keywords: ['flower', 'spring'], category: 'Nature' },
  { emoji: '🌱', name: 'seedling', keywords: ['plant', 'grow', 'sprout'], category: 'Nature' },
  { emoji: '🪴', name: 'potted plant', keywords: ['plant', 'house plant', 'pot'], category: 'Nature' },
  { emoji: '🌲', name: 'evergreen tree', keywords: ['tree', 'pine', 'forest'], category: 'Nature' },
  { emoji: '🌳', name: 'deciduous tree', keywords: ['tree', 'forest', 'nature'], category: 'Nature' },
  { emoji: '🌴', name: 'palm tree', keywords: ['tree', 'tropical', 'beach'], category: 'Nature' },
  { emoji: '🌵', name: 'cactus', keywords: ['cactus', 'desert'], category: 'Nature' },
  { emoji: '🍀', name: 'four leaf clover', keywords: ['luck', 'clover', 'irish'], category: 'Nature' },
  { emoji: '🍁', name: 'maple leaf', keywords: ['leaf', 'autumn', 'fall', 'canada'], category: 'Nature' },
  { emoji: '🍂', name: 'fallen leaf', keywords: ['leaf', 'autumn', 'fall'], category: 'Nature' },
  { emoji: '🍃', name: 'leaf fluttering in wind', keywords: ['leaf', 'wind', 'nature'], category: 'Nature' },
  { emoji: '🌍', name: 'globe showing Europe-Africa', keywords: ['earth', 'world', 'globe'], category: 'Nature' },
  { emoji: '🌎', name: 'globe showing Americas', keywords: ['earth', 'world', 'globe'], category: 'Nature' },
  { emoji: '🌏', name: 'globe showing Asia-Australia', keywords: ['earth', 'world', 'globe'], category: 'Nature' },
  { emoji: '🌑', name: 'new moon', keywords: ['moon', 'dark', 'night'], category: 'Nature' },
  { emoji: '🌕', name: 'full moon', keywords: ['moon', 'night'], category: 'Nature' },
  { emoji: '🌙', name: 'crescent moon', keywords: ['moon', 'night', 'sleep'], category: 'Nature' },
  { emoji: '⭐', name: 'star', keywords: ['star', 'night', 'favorite'], category: 'Nature' },
  { emoji: '🌟', name: 'glowing star', keywords: ['star', 'sparkle', 'shine'], category: 'Nature' },
  { emoji: '✨', name: 'sparkles', keywords: ['sparkle', 'magic', 'shine', 'star'], category: 'Nature' },
  { emoji: '⚡', name: 'high voltage', keywords: ['lightning', 'electric', 'power', 'energy'], category: 'Nature' },
  { emoji: '🔥', name: 'fire', keywords: ['fire', 'hot', 'flame', 'lit'], category: 'Nature' },
  { emoji: '💧', name: 'droplet', keywords: ['water', 'rain', 'drop'], category: 'Nature' },
  { emoji: '🌊', name: 'water wave', keywords: ['wave', 'ocean', 'sea', 'surf'], category: 'Nature' },
  { emoji: '❄️', name: 'snowflake', keywords: ['snow', 'cold', 'winter'], category: 'Nature' },
  { emoji: '☀️', name: 'sun', keywords: ['sun', 'sunny', 'bright', 'warm'], category: 'Nature' },
  { emoji: '🌈', name: 'rainbow', keywords: ['rainbow', 'color'], category: 'Nature' },
  { emoji: '☁️', name: 'cloud', keywords: ['cloud', 'weather'], category: 'Nature' },
  { emoji: '🌧️', name: 'cloud with rain', keywords: ['rain', 'weather'], category: 'Nature' },
  { emoji: '⛈️', name: 'cloud with lightning and rain', keywords: ['storm', 'thunder'], category: 'Nature' },
  { emoji: '🌪️', name: 'tornado', keywords: ['tornado', 'storm', 'wind'], category: 'Nature' },

  // Food
  { emoji: '🍎', name: 'red apple', keywords: ['apple', 'fruit', 'red'], category: 'Food' },
  { emoji: '🍐', name: 'pear', keywords: ['pear', 'fruit'], category: 'Food' },
  { emoji: '🍊', name: 'tangerine', keywords: ['orange', 'fruit', 'citrus'], category: 'Food' },
  { emoji: '🍋', name: 'lemon', keywords: ['lemon', 'fruit', 'citrus', 'sour'], category: 'Food' },
  { emoji: '🍌', name: 'banana', keywords: ['banana', 'fruit'], category: 'Food' },
  { emoji: '🍉', name: 'watermelon', keywords: ['watermelon', 'fruit', 'summer'], category: 'Food' },
  { emoji: '🍇', name: 'grapes', keywords: ['grapes', 'fruit', 'wine'], category: 'Food' },
  { emoji: '🍓', name: 'strawberry', keywords: ['strawberry', 'fruit', 'berry'], category: 'Food' },
  { emoji: '🫐', name: 'blueberries', keywords: ['blueberry', 'fruit', 'berry'], category: 'Food' },
  { emoji: '🍑', name: 'peach', keywords: ['peach', 'fruit'], category: 'Food' },
  { emoji: '🥭', name: 'mango', keywords: ['mango', 'fruit', 'tropical'], category: 'Food' },
  { emoji: '🍍', name: 'pineapple', keywords: ['pineapple', 'fruit', 'tropical'], category: 'Food' },
  { emoji: '🥥', name: 'coconut', keywords: ['coconut', 'tropical'], category: 'Food' },
  { emoji: '🥝', name: 'kiwi fruit', keywords: ['kiwi', 'fruit'], category: 'Food' },
  { emoji: '🍅', name: 'tomato', keywords: ['tomato', 'vegetable'], category: 'Food' },
  { emoji: '🥑', name: 'avocado', keywords: ['avocado', 'guacamole'], category: 'Food' },
  { emoji: '🥦', name: 'broccoli', keywords: ['broccoli', 'vegetable', 'green'], category: 'Food' },
  { emoji: '🥬', name: 'leafy green', keywords: ['lettuce', 'salad', 'vegetable'], category: 'Food' },
  { emoji: '🌽', name: 'ear of corn', keywords: ['corn', 'maize'], category: 'Food' },
  { emoji: '🌶️', name: 'hot pepper', keywords: ['pepper', 'spicy', 'chili'], category: 'Food' },
  { emoji: '🥕', name: 'carrot', keywords: ['carrot', 'vegetable', 'orange'], category: 'Food' },
  { emoji: '🧄', name: 'garlic', keywords: ['garlic', 'flavor'], category: 'Food' },
  { emoji: '🧅', name: 'onion', keywords: ['onion', 'vegetable'], category: 'Food' },
  { emoji: '🥔', name: 'potato', keywords: ['potato', 'vegetable'], category: 'Food' },
  { emoji: '🍞', name: 'bread', keywords: ['bread', 'loaf', 'toast'], category: 'Food' },
  { emoji: '🥐', name: 'croissant', keywords: ['croissant', 'french', 'pastry'], category: 'Food' },
  { emoji: '🥖', name: 'baguette bread', keywords: ['baguette', 'french', 'bread'], category: 'Food' },
  { emoji: '🧀', name: 'cheese wedge', keywords: ['cheese'], category: 'Food' },
  { emoji: '🥚', name: 'egg', keywords: ['egg', 'breakfast'], category: 'Food' },
  { emoji: '🍳', name: 'cooking', keywords: ['egg', 'frying', 'breakfast'], category: 'Food' },
  { emoji: '🥓', name: 'bacon', keywords: ['bacon', 'meat', 'breakfast'], category: 'Food' },
  { emoji: '🥩', name: 'cut of meat', keywords: ['steak', 'meat'], category: 'Food' },
  { emoji: '🍗', name: 'poultry leg', keywords: ['chicken', 'drumstick'], category: 'Food' },
  { emoji: '🍖', name: 'meat on bone', keywords: ['meat', 'bone'], category: 'Food' },
  { emoji: '🌭', name: 'hot dog', keywords: ['hotdog', 'sausage'], category: 'Food' },
  { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'fast food'], category: 'Food' },
  { emoji: '🍟', name: 'french fries', keywords: ['fries', 'fast food'], category: 'Food' },
  { emoji: '🍕', name: 'pizza', keywords: ['pizza', 'pie'], category: 'Food' },
  { emoji: '🥪', name: 'sandwich', keywords: ['sandwich', 'lunch'], category: 'Food' },
  { emoji: '🌮', name: 'taco', keywords: ['taco', 'mexican'], category: 'Food' },
  { emoji: '🌯', name: 'burrito', keywords: ['burrito', 'wrap', 'mexican'], category: 'Food' },
  { emoji: '🥗', name: 'green salad', keywords: ['salad', 'healthy'], category: 'Food' },
  { emoji: '🍝', name: 'spaghetti', keywords: ['pasta', 'noodles', 'italian'], category: 'Food' },
  { emoji: '🍜', name: 'steaming bowl', keywords: ['ramen', 'noodles', 'soup'], category: 'Food' },
  { emoji: '🍲', name: 'pot of food', keywords: ['stew', 'soup', 'pot'], category: 'Food' },
  { emoji: '🍣', name: 'sushi', keywords: ['sushi', 'japanese', 'fish'], category: 'Food' },
  { emoji: '🍱', name: 'bento box', keywords: ['bento', 'japanese', 'lunch'], category: 'Food' },
  { emoji: '🍰', name: 'shortcake', keywords: ['cake', 'dessert', 'strawberry'], category: 'Food' },
  { emoji: '🎂', name: 'birthday cake', keywords: ['cake', 'birthday', 'party'], category: 'Food' },
  { emoji: '🧁', name: 'cupcake', keywords: ['cupcake', 'muffin', 'dessert'], category: 'Food' },
  { emoji: '🍩', name: 'doughnut', keywords: ['donut', 'dessert'], category: 'Food' },
  { emoji: '🍪', name: 'cookie', keywords: ['cookie', 'dessert', 'biscuit'], category: 'Food' },
  { emoji: '🍫', name: 'chocolate bar', keywords: ['chocolate', 'candy', 'dessert'], category: 'Food' },
  { emoji: '🍬', name: 'candy', keywords: ['candy', 'sweet'], category: 'Food' },
  { emoji: '🍭', name: 'lollipop', keywords: ['candy', 'lollipop', 'sweet'], category: 'Food' },
  { emoji: '🍦', name: 'soft ice cream', keywords: ['ice cream', 'dessert'], category: 'Food' },
  { emoji: '☕', name: 'hot beverage', keywords: ['coffee', 'tea', 'hot', 'drink'], category: 'Food' },
  { emoji: '🍵', name: 'teacup without handle', keywords: ['tea', 'green tea', 'drink'], category: 'Food' },
  { emoji: '🧃', name: 'beverage box', keywords: ['juice', 'drink', 'box'], category: 'Food' },
  { emoji: '🥤', name: 'cup with straw', keywords: ['soda', 'drink', 'straw'], category: 'Food' },
  { emoji: '🧋', name: 'bubble tea', keywords: ['boba', 'bubble tea', 'drink'], category: 'Food' },
  { emoji: '🍺', name: 'beer mug', keywords: ['beer', 'drink', 'alcohol'], category: 'Food' },
  { emoji: '🍷', name: 'wine glass', keywords: ['wine', 'drink', 'alcohol'], category: 'Food' },
  { emoji: '🥂', name: 'clinking glasses', keywords: ['cheers', 'champagne', 'celebrate'], category: 'Food' },
  { emoji: '🥃', name: 'tumbler glass', keywords: ['whiskey', 'drink', 'alcohol'], category: 'Food' },
  { emoji: '🍸', name: 'cocktail glass', keywords: ['martini', 'cocktail', 'drink'], category: 'Food' },

  // Activities
  { emoji: '⚽', name: 'soccer ball', keywords: ['soccer', 'football', 'sport'], category: 'Activities' },
  { emoji: '🏀', name: 'basketball', keywords: ['basketball', 'sport'], category: 'Activities' },
  { emoji: '🏈', name: 'american football', keywords: ['football', 'sport'], category: 'Activities' },
  { emoji: '⚾', name: 'baseball', keywords: ['baseball', 'sport'], category: 'Activities' },
  { emoji: '🥎', name: 'softball', keywords: ['softball', 'sport'], category: 'Activities' },
  { emoji: '🎾', name: 'tennis', keywords: ['tennis', 'sport', 'racket'], category: 'Activities' },
  { emoji: '🏐', name: 'volleyball', keywords: ['volleyball', 'sport'], category: 'Activities' },
  { emoji: '🏉', name: 'rugby football', keywords: ['rugby', 'sport'], category: 'Activities' },
  { emoji: '🎱', name: 'pool 8 ball', keywords: ['billiards', 'pool'], category: 'Activities' },
  { emoji: '🏓', name: 'ping pong', keywords: ['table tennis', 'sport'], category: 'Activities' },
  { emoji: '🏸', name: 'badminton', keywords: ['badminton', 'sport'], category: 'Activities' },
  { emoji: '🥊', name: 'boxing glove', keywords: ['boxing', 'fight', 'sport'], category: 'Activities' },
  { emoji: '🥋', name: 'martial arts uniform', keywords: ['karate', 'judo', 'martial arts'], category: 'Activities' },
  { emoji: '⛳', name: 'flag in hole', keywords: ['golf', 'sport'], category: 'Activities' },
  { emoji: '⛸️', name: 'ice skate', keywords: ['ice skating', 'sport', 'winter'], category: 'Activities' },
  { emoji: '🎿', name: 'skis', keywords: ['ski', 'sport', 'winter', 'snow'], category: 'Activities' },
  { emoji: '🛹', name: 'skateboard', keywords: ['skateboard', 'sport'], category: 'Activities' },
  { emoji: '🏂', name: 'snowboarder', keywords: ['snowboard', 'sport', 'winter'], category: 'Activities' },
  { emoji: '🏋️', name: 'person lifting weights', keywords: ['gym', 'workout', 'weights'], category: 'Activities' },
  { emoji: '🤸', name: 'person cartwheeling', keywords: ['gymnastics', 'cartwheel'], category: 'Activities' },
  { emoji: '🚴', name: 'person biking', keywords: ['bike', 'cycle', 'bicycle'], category: 'Activities' },
  { emoji: '🏊', name: 'person swimming', keywords: ['swim', 'pool'], category: 'Activities' },
  { emoji: '🧘', name: 'person in lotus position', keywords: ['yoga', 'meditate', 'zen'], category: 'Activities' },
  { emoji: '🎮', name: 'video game', keywords: ['game', 'controller', 'gaming'], category: 'Activities' },
  { emoji: '🕹️', name: 'joystick', keywords: ['game', 'arcade', 'gaming'], category: 'Activities' },
  { emoji: '🎲', name: 'game die', keywords: ['dice', 'game', 'random'], category: 'Activities' },
  { emoji: '🧩', name: 'puzzle piece', keywords: ['puzzle', 'jigsaw'], category: 'Activities' },
  { emoji: '♟️', name: 'chess pawn', keywords: ['chess', 'game', 'strategy'], category: 'Activities' },
  { emoji: '🎯', name: 'bullseye', keywords: ['target', 'dart', 'goal', 'aim'], category: 'Activities' },
  { emoji: '🎪', name: 'circus tent', keywords: ['circus', 'carnival'], category: 'Activities' },
  { emoji: '🎭', name: 'performing arts', keywords: ['theater', 'drama', 'mask'], category: 'Activities' },
  { emoji: '🎨', name: 'artist palette', keywords: ['art', 'paint', 'color', 'creative'], category: 'Activities' },
  { emoji: '🎬', name: 'clapper board', keywords: ['movie', 'film', 'cinema'], category: 'Activities' },
  { emoji: '🎤', name: 'microphone', keywords: ['mic', 'sing', 'karaoke', 'music'], category: 'Activities' },
  { emoji: '🎧', name: 'headphone', keywords: ['headphones', 'music', 'audio'], category: 'Activities' },
  { emoji: '🎵', name: 'musical note', keywords: ['music', 'note', 'song'], category: 'Activities' },
  { emoji: '🎶', name: 'musical notes', keywords: ['music', 'notes', 'melody'], category: 'Activities' },
  { emoji: '🎹', name: 'musical keyboard', keywords: ['piano', 'music', 'keys'], category: 'Activities' },
  { emoji: '🥁', name: 'drum', keywords: ['drum', 'music', 'beat'], category: 'Activities' },
  { emoji: '🎸', name: 'guitar', keywords: ['guitar', 'music', 'rock'], category: 'Activities' },
  { emoji: '🎺', name: 'trumpet', keywords: ['trumpet', 'music', 'brass'], category: 'Activities' },
  { emoji: '🎻', name: 'violin', keywords: ['violin', 'music', 'classical'], category: 'Activities' },
  { emoji: '🎪', name: 'circus tent', keywords: ['circus', 'carnival'], category: 'Activities' },
  { emoji: '🏆', name: 'trophy', keywords: ['trophy', 'win', 'award', 'champion'], category: 'Activities' },
  { emoji: '🥇', name: 'gold medal', keywords: ['medal', 'gold', 'first', 'winner'], category: 'Activities' },
  { emoji: '🥈', name: 'silver medal', keywords: ['medal', 'silver', 'second'], category: 'Activities' },
  { emoji: '🥉', name: 'bronze medal', keywords: ['medal', 'bronze', 'third'], category: 'Activities' },
  { emoji: '🏅', name: 'sports medal', keywords: ['medal', 'award'], category: 'Activities' },
  { emoji: '🎖️', name: 'military medal', keywords: ['medal', 'honor'], category: 'Activities' },
  { emoji: '🎗️', name: 'reminder ribbon', keywords: ['ribbon', 'awareness'], category: 'Activities' },
  { emoji: '🎁', name: 'wrapped gift', keywords: ['gift', 'present', 'birthday'], category: 'Activities' },
  { emoji: '🎉', name: 'party popper', keywords: ['party', 'celebrate', 'congratulations'], category: 'Activities' },
  { emoji: '🎊', name: 'confetti ball', keywords: ['confetti', 'celebrate', 'party'], category: 'Activities' },
  { emoji: '🎈', name: 'balloon', keywords: ['balloon', 'party', 'birthday'], category: 'Activities' },
  { emoji: '🎀', name: 'ribbon', keywords: ['ribbon', 'gift', 'bow'], category: 'Activities' },
  { emoji: '🎄', name: 'Christmas tree', keywords: ['christmas', 'tree', 'holiday'], category: 'Activities' },
  { emoji: '🎃', name: 'jack-o-lantern', keywords: ['halloween', 'pumpkin'], category: 'Activities' },
  { emoji: '🎆', name: 'fireworks', keywords: ['fireworks', 'celebrate', 'new year'], category: 'Activities' },
  { emoji: '🎇', name: 'sparkler', keywords: ['sparkler', 'fireworks', 'celebrate'], category: 'Activities' },

  // Travel
  { emoji: '🚗', name: 'automobile', keywords: ['car', 'vehicle', 'drive'], category: 'Travel' },
  { emoji: '🚕', name: 'taxi', keywords: ['taxi', 'cab', 'car'], category: 'Travel' },
  { emoji: '🚌', name: 'bus', keywords: ['bus', 'transit'], category: 'Travel' },
  { emoji: '🚎', name: 'trolleybus', keywords: ['bus', 'trolley'], category: 'Travel' },
  { emoji: '🏎️', name: 'racing car', keywords: ['race', 'car', 'fast'], category: 'Travel' },
  { emoji: '🚓', name: 'police car', keywords: ['police', 'car', 'law'], category: 'Travel' },
  { emoji: '🚑', name: 'ambulance', keywords: ['ambulance', 'emergency', 'hospital'], category: 'Travel' },
  { emoji: '🚒', name: 'fire engine', keywords: ['fire', 'truck', 'emergency'], category: 'Travel' },
  { emoji: '🚐', name: 'minibus', keywords: ['van', 'bus'], category: 'Travel' },
  { emoji: '🛻', name: 'pickup truck', keywords: ['truck', 'vehicle'], category: 'Travel' },
  { emoji: '🚚', name: 'delivery truck', keywords: ['truck', 'delivery'], category: 'Travel' },
  { emoji: '🚲', name: 'bicycle', keywords: ['bike', 'cycle', 'bicycle'], category: 'Travel' },
  { emoji: '🛵', name: 'motor scooter', keywords: ['scooter', 'motorcycle'], category: 'Travel' },
  { emoji: '🏍️', name: 'motorcycle', keywords: ['motorcycle', 'bike'], category: 'Travel' },
  { emoji: '🚂', name: 'locomotive', keywords: ['train', 'steam'], category: 'Travel' },
  { emoji: '🚆', name: 'train', keywords: ['train', 'rail'], category: 'Travel' },
  { emoji: '✈️', name: 'airplane', keywords: ['plane', 'fly', 'travel', 'flight'], category: 'Travel' },
  { emoji: '🛩️', name: 'small airplane', keywords: ['plane', 'fly'], category: 'Travel' },
  { emoji: '🚀', name: 'rocket', keywords: ['rocket', 'space', 'launch', 'ship'], category: 'Travel' },
  { emoji: '🛸', name: 'flying saucer', keywords: ['ufo', 'alien', 'space'], category: 'Travel' },
  { emoji: '🚁', name: 'helicopter', keywords: ['helicopter', 'fly'], category: 'Travel' },
  { emoji: '⛵', name: 'sailboat', keywords: ['boat', 'sail', 'sea'], category: 'Travel' },
  { emoji: '🚤', name: 'speedboat', keywords: ['boat', 'fast', 'sea'], category: 'Travel' },
  { emoji: '🛥️', name: 'motor boat', keywords: ['boat', 'sea'], category: 'Travel' },
  { emoji: '🚢', name: 'ship', keywords: ['ship', 'boat', 'cruise'], category: 'Travel' },
  { emoji: '⛽', name: 'fuel pump', keywords: ['gas', 'fuel', 'station'], category: 'Travel' },
  { emoji: '🏠', name: 'house', keywords: ['house', 'home'], category: 'Travel' },
  { emoji: '🏡', name: 'house with garden', keywords: ['house', 'home', 'garden'], category: 'Travel' },
  { emoji: '🏢', name: 'office building', keywords: ['office', 'building', 'work'], category: 'Travel' },
  { emoji: '🏥', name: 'hospital', keywords: ['hospital', 'medical'], category: 'Travel' },
  { emoji: '🏦', name: 'bank', keywords: ['bank', 'money', 'finance'], category: 'Travel' },
  { emoji: '🏨', name: 'hotel', keywords: ['hotel', 'travel', 'stay'], category: 'Travel' },
  { emoji: '🏪', name: 'convenience store', keywords: ['store', 'shop'], category: 'Travel' },
  { emoji: '🏫', name: 'school', keywords: ['school', 'education'], category: 'Travel' },
  { emoji: '🏛️', name: 'classical building', keywords: ['building', 'government', 'museum'], category: 'Travel' },
  { emoji: '⛪', name: 'church', keywords: ['church', 'religion'], category: 'Travel' },
  { emoji: '🕌', name: 'mosque', keywords: ['mosque', 'religion', 'islam'], category: 'Travel' },
  { emoji: '🗽', name: 'Statue of Liberty', keywords: ['liberty', 'new york', 'usa'], category: 'Travel' },
  { emoji: '🗼', name: 'Tokyo tower', keywords: ['tower', 'tokyo', 'japan'], category: 'Travel' },
  { emoji: '🏰', name: 'castle', keywords: ['castle', 'medieval'], category: 'Travel' },
  { emoji: '🗻', name: 'mount fuji', keywords: ['mountain', 'japan', 'fuji'], category: 'Travel' },
  { emoji: '🏕️', name: 'camping', keywords: ['camp', 'tent', 'outdoor'], category: 'Travel' },
  { emoji: '🏖️', name: 'beach with umbrella', keywords: ['beach', 'vacation', 'sun'], category: 'Travel' },
  { emoji: '🏜️', name: 'desert', keywords: ['desert', 'sand'], category: 'Travel' },
  { emoji: '🌋', name: 'volcano', keywords: ['volcano', 'lava'], category: 'Travel' },

  // Objects
  { emoji: '⌚', name: 'watch', keywords: ['watch', 'time', 'clock'], category: 'Objects' },
  { emoji: '📱', name: 'mobile phone', keywords: ['phone', 'mobile', 'cell', 'smartphone'], category: 'Objects' },
  { emoji: '💻', name: 'laptop', keywords: ['laptop', 'computer', 'pc', 'mac'], category: 'Objects' },
  { emoji: '⌨️', name: 'keyboard', keywords: ['keyboard', 'type', 'computer'], category: 'Objects' },
  { emoji: '🖥️', name: 'desktop computer', keywords: ['computer', 'desktop', 'monitor'], category: 'Objects' },
  { emoji: '🖨️', name: 'printer', keywords: ['printer', 'print'], category: 'Objects' },
  { emoji: '🖱️', name: 'computer mouse', keywords: ['mouse', 'click', 'computer'], category: 'Objects' },
  { emoji: '💽', name: 'computer disk', keywords: ['disk', 'storage'], category: 'Objects' },
  { emoji: '💾', name: 'floppy disk', keywords: ['save', 'floppy', 'disk'], category: 'Objects' },
  { emoji: '💿', name: 'optical disk', keywords: ['cd', 'dvd', 'disc'], category: 'Objects' },
  { emoji: '📀', name: 'dvd', keywords: ['dvd', 'disc', 'movie'], category: 'Objects' },
  { emoji: '🎥', name: 'movie camera', keywords: ['camera', 'movie', 'film', 'video'], category: 'Objects' },
  { emoji: '📷', name: 'camera', keywords: ['camera', 'photo', 'picture'], category: 'Objects' },
  { emoji: '📸', name: 'camera with flash', keywords: ['camera', 'photo', 'flash'], category: 'Objects' },
  { emoji: '📹', name: 'video camera', keywords: ['video', 'camera', 'record'], category: 'Objects' },
  { emoji: '📺', name: 'television', keywords: ['tv', 'television', 'watch'], category: 'Objects' },
  { emoji: '📻', name: 'radio', keywords: ['radio', 'music', 'broadcast'], category: 'Objects' },
  { emoji: '🔋', name: 'battery', keywords: ['battery', 'power', 'charge'], category: 'Objects' },
  { emoji: '🔌', name: 'electric plug', keywords: ['plug', 'electric', 'power'], category: 'Objects' },
  { emoji: '💡', name: 'light bulb', keywords: ['idea', 'light', 'bulb', 'bright'], category: 'Objects' },
  { emoji: '🔦', name: 'flashlight', keywords: ['flashlight', 'torch', 'light'], category: 'Objects' },
  { emoji: '🕯️', name: 'candle', keywords: ['candle', 'light', 'fire'], category: 'Objects' },
  { emoji: '📚', name: 'books', keywords: ['books', 'read', 'library', 'study'], category: 'Objects' },
  { emoji: '📖', name: 'open book', keywords: ['book', 'read', 'open'], category: 'Objects' },
  { emoji: '📝', name: 'memo', keywords: ['memo', 'note', 'write', 'pencil'], category: 'Objects' },
  { emoji: '✏️', name: 'pencil', keywords: ['pencil', 'write', 'draw'], category: 'Objects' },
  { emoji: '🖊️', name: 'pen', keywords: ['pen', 'write'], category: 'Objects' },
  { emoji: '📎', name: 'paperclip', keywords: ['paperclip', 'attach', 'clip'], category: 'Objects' },
  { emoji: '📌', name: 'pushpin', keywords: ['pin', 'pushpin', 'location'], category: 'Objects' },
  { emoji: '📐', name: 'triangular ruler', keywords: ['ruler', 'triangle', 'math'], category: 'Objects' },
  { emoji: '📏', name: 'straight ruler', keywords: ['ruler', 'measure'], category: 'Objects' },
  { emoji: '✂️', name: 'scissors', keywords: ['scissors', 'cut'], category: 'Objects' },
  { emoji: '📁', name: 'file folder', keywords: ['folder', 'file', 'directory'], category: 'Objects' },
  { emoji: '📂', name: 'open file folder', keywords: ['folder', 'file', 'open'], category: 'Objects' },
  { emoji: '🗂️', name: 'card index dividers', keywords: ['organize', 'index', 'divider'], category: 'Objects' },
  { emoji: '📅', name: 'calendar', keywords: ['calendar', 'date', 'schedule'], category: 'Objects' },
  { emoji: '📆', name: 'tear-off calendar', keywords: ['calendar', 'date'], category: 'Objects' },
  { emoji: '🗓️', name: 'spiral calendar', keywords: ['calendar', 'planner'], category: 'Objects' },
  { emoji: '📊', name: 'bar chart', keywords: ['chart', 'graph', 'data', 'analytics'], category: 'Objects' },
  { emoji: '📈', name: 'chart increasing', keywords: ['chart', 'graph', 'up', 'growth'], category: 'Objects' },
  { emoji: '📉', name: 'chart decreasing', keywords: ['chart', 'graph', 'down', 'decline'], category: 'Objects' },
  { emoji: '📋', name: 'clipboard', keywords: ['clipboard', 'paste', 'list'], category: 'Objects' },
  { emoji: '🔑', name: 'key', keywords: ['key', 'lock', 'password'], category: 'Objects' },
  { emoji: '🗝️', name: 'old key', keywords: ['key', 'lock', 'vintage'], category: 'Objects' },
  { emoji: '🔒', name: 'locked', keywords: ['lock', 'secure', 'closed'], category: 'Objects' },
  { emoji: '🔓', name: 'unlocked', keywords: ['unlock', 'open'], category: 'Objects' },
  { emoji: '🔧', name: 'wrench', keywords: ['wrench', 'tool', 'fix'], category: 'Objects' },
  { emoji: '🔨', name: 'hammer', keywords: ['hammer', 'tool', 'build'], category: 'Objects' },
  { emoji: '🛠️', name: 'hammer and wrench', keywords: ['tools', 'fix', 'build'], category: 'Objects' },
  { emoji: '⚙️', name: 'gear', keywords: ['gear', 'settings', 'cog'], category: 'Objects' },
  { emoji: '🧲', name: 'magnet', keywords: ['magnet', 'attract'], category: 'Objects' },
  { emoji: '🧪', name: 'test tube', keywords: ['test', 'science', 'lab', 'experiment'], category: 'Objects' },
  { emoji: '🧬', name: 'dna', keywords: ['dna', 'science', 'gene', 'biology'], category: 'Objects' },
  { emoji: '🔬', name: 'microscope', keywords: ['microscope', 'science', 'lab'], category: 'Objects' },
  { emoji: '🔭', name: 'telescope', keywords: ['telescope', 'space', 'astronomy'], category: 'Objects' },
  { emoji: '📡', name: 'satellite antenna', keywords: ['satellite', 'antenna', 'signal'], category: 'Objects' },
  { emoji: '💉', name: 'syringe', keywords: ['syringe', 'needle', 'vaccine'], category: 'Objects' },
  { emoji: '💊', name: 'pill', keywords: ['pill', 'medicine', 'drug'], category: 'Objects' },
  { emoji: '🩹', name: 'adhesive bandage', keywords: ['bandaid', 'bandage', 'heal'], category: 'Objects' },
  { emoji: '🪣', name: 'bucket', keywords: ['bucket', 'pail'], category: 'Objects' },
  { emoji: '🧯', name: 'fire extinguisher', keywords: ['fire', 'extinguisher', 'safety'], category: 'Objects' },
  { emoji: '💎', name: 'gem stone', keywords: ['diamond', 'gem', 'jewel', 'precious'], category: 'Objects' },
  { emoji: '🪙', name: 'coin', keywords: ['coin', 'money', 'currency'], category: 'Objects' },
  { emoji: '💰', name: 'money bag', keywords: ['money', 'bag', 'dollar', 'rich'], category: 'Objects' },
  { emoji: '💵', name: 'dollar banknote', keywords: ['money', 'dollar', 'cash'], category: 'Objects' },
  { emoji: '💳', name: 'credit card', keywords: ['credit', 'card', 'payment'], category: 'Objects' },
  { emoji: '✉️', name: 'envelope', keywords: ['email', 'mail', 'letter'], category: 'Objects' },
  { emoji: '📧', name: 'e-mail', keywords: ['email', 'mail'], category: 'Objects' },
  { emoji: '📦', name: 'package', keywords: ['package', 'box', 'shipping'], category: 'Objects' },
  { emoji: '🏷️', name: 'label', keywords: ['tag', 'label', 'price'], category: 'Objects' },

  // Symbols
  { emoji: '❤️', name: 'red heart', keywords: ['heart', 'love', 'red'], category: 'Symbols' },
  { emoji: '🧡', name: 'orange heart', keywords: ['heart', 'love', 'orange'], category: 'Symbols' },
  { emoji: '💛', name: 'yellow heart', keywords: ['heart', 'love', 'yellow'], category: 'Symbols' },
  { emoji: '💚', name: 'green heart', keywords: ['heart', 'love', 'green'], category: 'Symbols' },
  { emoji: '💙', name: 'blue heart', keywords: ['heart', 'love', 'blue'], category: 'Symbols' },
  { emoji: '💜', name: 'purple heart', keywords: ['heart', 'love', 'purple'], category: 'Symbols' },
  { emoji: '🖤', name: 'black heart', keywords: ['heart', 'love', 'black'], category: 'Symbols' },
  { emoji: '🤍', name: 'white heart', keywords: ['heart', 'love', 'white'], category: 'Symbols' },
  { emoji: '🤎', name: 'brown heart', keywords: ['heart', 'love', 'brown'], category: 'Symbols' },
  { emoji: '💔', name: 'broken heart', keywords: ['heart', 'broken', 'sad'], category: 'Symbols' },
  { emoji: '❣️', name: 'heart exclamation', keywords: ['heart', 'love', 'exclamation'], category: 'Symbols' },
  { emoji: '💕', name: 'two hearts', keywords: ['hearts', 'love'], category: 'Symbols' },
  { emoji: '💞', name: 'revolving hearts', keywords: ['hearts', 'love'], category: 'Symbols' },
  { emoji: '💓', name: 'beating heart', keywords: ['heart', 'love', 'beat'], category: 'Symbols' },
  { emoji: '💗', name: 'growing heart', keywords: ['heart', 'love', 'grow'], category: 'Symbols' },
  { emoji: '💖', name: 'sparkling heart', keywords: ['heart', 'love', 'sparkle'], category: 'Symbols' },
  { emoji: '💘', name: 'heart with arrow', keywords: ['heart', 'love', 'cupid'], category: 'Symbols' },
  { emoji: '💝', name: 'heart with ribbon', keywords: ['heart', 'love', 'gift'], category: 'Symbols' },
  { emoji: '💟', name: 'heart decoration', keywords: ['heart', 'love'], category: 'Symbols' },
  { emoji: '☮️', name: 'peace symbol', keywords: ['peace'], category: 'Symbols' },
  { emoji: '✝️', name: 'latin cross', keywords: ['cross', 'religion', 'christian'], category: 'Symbols' },
  { emoji: '☪️', name: 'star and crescent', keywords: ['islam', 'religion'], category: 'Symbols' },
  { emoji: '🕉️', name: 'om', keywords: ['om', 'hinduism', 'religion'], category: 'Symbols' },
  { emoji: '☯️', name: 'yin yang', keywords: ['yin', 'yang', 'balance'], category: 'Symbols' },
  { emoji: '✡️', name: 'star of David', keywords: ['jewish', 'religion'], category: 'Symbols' },
  { emoji: '♻️', name: 'recycling symbol', keywords: ['recycle', 'environment', 'green'], category: 'Symbols' },
  { emoji: '⚠️', name: 'warning', keywords: ['warning', 'caution', 'danger'], category: 'Symbols' },
  { emoji: '🚫', name: 'prohibited', keywords: ['no', 'forbidden', 'stop'], category: 'Symbols' },
  { emoji: '❌', name: 'cross mark', keywords: ['no', 'wrong', 'cancel', 'x'], category: 'Symbols' },
  { emoji: '⭕', name: 'hollow red circle', keywords: ['circle', 'ring'], category: 'Symbols' },
  { emoji: '❓', name: 'red question mark', keywords: ['question', 'confused', 'what'], category: 'Symbols' },
  { emoji: '❗', name: 'red exclamation mark', keywords: ['exclamation', 'important', 'alert'], category: 'Symbols' },
  { emoji: '‼️', name: 'double exclamation mark', keywords: ['exclamation', 'alert'], category: 'Symbols' },
  { emoji: '⁉️', name: 'exclamation question mark', keywords: ['exclamation', 'question', 'wtf'], category: 'Symbols' },
  { emoji: '💯', name: 'hundred points', keywords: ['100', 'perfect', 'score'], category: 'Symbols' },
  { emoji: '🔴', name: 'red circle', keywords: ['red', 'circle', 'dot'], category: 'Symbols' },
  { emoji: '🟠', name: 'orange circle', keywords: ['orange', 'circle', 'dot'], category: 'Symbols' },
  { emoji: '🟡', name: 'yellow circle', keywords: ['yellow', 'circle', 'dot'], category: 'Symbols' },
  { emoji: '🟢', name: 'green circle', keywords: ['green', 'circle', 'dot'], category: 'Symbols' },
  { emoji: '🔵', name: 'blue circle', keywords: ['blue', 'circle', 'dot'], category: 'Symbols' },
  { emoji: '🟣', name: 'purple circle', keywords: ['purple', 'circle', 'dot'], category: 'Symbols' },
  { emoji: '⚫', name: 'black circle', keywords: ['black', 'circle', 'dot'], category: 'Symbols' },
  { emoji: '⚪', name: 'white circle', keywords: ['white', 'circle', 'dot'], category: 'Symbols' },
  { emoji: '🟤', name: 'brown circle', keywords: ['brown', 'circle', 'dot'], category: 'Symbols' },
  { emoji: '🔶', name: 'large orange diamond', keywords: ['diamond', 'orange'], category: 'Symbols' },
  { emoji: '🔷', name: 'large blue diamond', keywords: ['diamond', 'blue'], category: 'Symbols' },
  { emoji: '🔺', name: 'red triangle pointed up', keywords: ['triangle', 'up', 'red'], category: 'Symbols' },
  { emoji: '🔻', name: 'red triangle pointed down', keywords: ['triangle', 'down', 'red'], category: 'Symbols' },
  { emoji: '▶️', name: 'play button', keywords: ['play', 'start'], category: 'Symbols' },
  { emoji: '⏸️', name: 'pause button', keywords: ['pause', 'break'], category: 'Symbols' },
  { emoji: '⏹️', name: 'stop button', keywords: ['stop', 'end'], category: 'Symbols' },
  { emoji: '⏩', name: 'fast forward button', keywords: ['fast', 'forward', 'skip'], category: 'Symbols' },
  { emoji: '⏪', name: 'fast reverse button', keywords: ['rewind', 'reverse'], category: 'Symbols' },
  { emoji: '🔀', name: 'shuffle tracks button', keywords: ['shuffle', 'random'], category: 'Symbols' },
  { emoji: '🔁', name: 'repeat button', keywords: ['repeat', 'loop'], category: 'Symbols' },
  { emoji: '🔂', name: 'repeat single button', keywords: ['repeat', 'one'], category: 'Symbols' },
  { emoji: '➕', name: 'plus', keywords: ['plus', 'add'], category: 'Symbols' },
  { emoji: '➖', name: 'minus', keywords: ['minus', 'subtract', 'remove'], category: 'Symbols' },
  { emoji: '➗', name: 'divide', keywords: ['divide', 'division', 'math'], category: 'Symbols' },
  { emoji: '✖️', name: 'multiply', keywords: ['multiply', 'times', 'math'], category: 'Symbols' },
  { emoji: '♾️', name: 'infinity', keywords: ['infinity', 'forever', 'infinite'], category: 'Symbols' },
  { emoji: '💲', name: 'heavy dollar sign', keywords: ['dollar', 'money'], category: 'Symbols' },
  { emoji: '™️', name: 'trade mark', keywords: ['trademark', 'brand'], category: 'Symbols' },
  { emoji: '©️', name: 'copyright', keywords: ['copyright', 'legal'], category: 'Symbols' },
  { emoji: '®️', name: 'registered', keywords: ['registered', 'brand', 'legal'], category: 'Symbols' },
  { emoji: '🔗', name: 'link', keywords: ['link', 'chain', 'url'], category: 'Symbols' },
  { emoji: '#️⃣', name: 'keycap hash', keywords: ['hash', 'number', 'hashtag'], category: 'Symbols' },
  { emoji: '*️⃣', name: 'keycap asterisk', keywords: ['asterisk', 'star'], category: 'Symbols' },
  { emoji: '0️⃣', name: 'keycap 0', keywords: ['zero', 'number'], category: 'Symbols' },
  { emoji: '1️⃣', name: 'keycap 1', keywords: ['one', 'number'], category: 'Symbols' },
  { emoji: '2️⃣', name: 'keycap 2', keywords: ['two', 'number'], category: 'Symbols' },
  { emoji: '3️⃣', name: 'keycap 3', keywords: ['three', 'number'], category: 'Symbols' },
  { emoji: '🔠', name: 'input latin uppercase', keywords: ['uppercase', 'letters', 'abc'], category: 'Symbols' },
  { emoji: '🔡', name: 'input latin lowercase', keywords: ['lowercase', 'letters'], category: 'Symbols' },
  { emoji: '🔢', name: 'input numbers', keywords: ['numbers', '123'], category: 'Symbols' },
  { emoji: '🆕', name: 'NEW button', keywords: ['new'], category: 'Symbols' },
  { emoji: '🆗', name: 'OK button', keywords: ['ok', 'okay'], category: 'Symbols' },
  { emoji: '🆙', name: 'UP! button', keywords: ['up', 'update'], category: 'Symbols' },
  { emoji: '🆒', name: 'COOL button', keywords: ['cool'], category: 'Symbols' },
  { emoji: '🆓', name: 'FREE button', keywords: ['free'], category: 'Symbols' },
  { emoji: '🏁', name: 'chequered flag', keywords: ['flag', 'finish', 'race'], category: 'Symbols' },
  { emoji: '🚩', name: 'triangular flag', keywords: ['flag', 'red flag'], category: 'Symbols' },
  { emoji: '🎌', name: 'crossed flags', keywords: ['flag', 'japan'], category: 'Symbols' },
  { emoji: '🏳️', name: 'white flag', keywords: ['flag', 'surrender'], category: 'Symbols' },
  { emoji: '🏴', name: 'black flag', keywords: ['flag', 'pirate'], category: 'Symbols' },
  { emoji: '✅', name: 'check mark button', keywords: ['check', 'done', 'complete', 'yes'], category: 'Symbols' },
  { emoji: '☑️', name: 'check box with check', keywords: ['check', 'checkbox', 'done'], category: 'Symbols' },
  { emoji: '⬆️', name: 'up arrow', keywords: ['up', 'arrow'], category: 'Symbols' },
  { emoji: '⬇️', name: 'down arrow', keywords: ['down', 'arrow'], category: 'Symbols' },
  { emoji: '⬅️', name: 'left arrow', keywords: ['left', 'arrow'], category: 'Symbols' },
  { emoji: '➡️', name: 'right arrow', keywords: ['right', 'arrow'], category: 'Symbols' },
  { emoji: '↩️', name: 'right arrow curving left', keywords: ['return', 'back', 'undo'], category: 'Symbols' },
  { emoji: '↪️', name: 'left arrow curving right', keywords: ['forward', 'redo'], category: 'Symbols' },
  { emoji: '🔃', name: 'clockwise vertical arrows', keywords: ['refresh', 'reload', 'rotate'], category: 'Symbols' },
  { emoji: '🔄', name: 'counterclockwise arrows button', keywords: ['refresh', 'sync', 'reload'], category: 'Symbols' },
]

// Lazy-loaded memoized data grouped by category
let _byCategory: Map<EmojiCategory, EmojiEntry[]> | null = null

export function getEmojisByCategory(): Map<EmojiCategory, EmojiEntry[]> {
  if (!_byCategory) {
    _byCategory = new Map()
    for (const cat of CATEGORIES) {
      _byCategory.set(cat, [])
    }
    for (const entry of EMOJI_DATA) {
      _byCategory.get(entry.category)!.push(entry)
    }
  }
  return _byCategory
}

export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.toLowerCase().trim()
  if (!q) return EMOJI_DATA

  return EMOJI_DATA.filter((entry) => {
    if (entry.name.toLowerCase().includes(q)) return true
    return entry.keywords.some((kw) => kw.includes(q))
  })
}

export function getRecentEmojis(): string[] {
  try {
    const stored = localStorage.getItem(RECENTLY_USED_KEY)
    if (!stored) return []
    return JSON.parse(stored) as string[]
  } catch {
    return []
  }
}

export function addRecentEmoji(emoji: string): void {
  const recent = getRecentEmojis().filter((e) => e !== emoji)
  recent.unshift(emoji)
  if (recent.length > MAX_RECENT) recent.length = MAX_RECENT
  try {
    localStorage.setItem(RECENTLY_USED_KEY, JSON.stringify(recent))
  } catch {
    // localStorage full or unavailable
  }
}
